const data = [
  {
    id: "1",
    images: "./images/allwell.png",
    desc: "AllWell",
    descs:
      "Ambroxol + Guaifenesin + Terbutaline is a combination of three medicines: Ambroxol , Guaifenesin and Terbutaline, which relieves cough with mucus.Ambroxol is a mucolytic which thins and loosens mucus (phlegm), making it easier to cough out.Guaifenesin is an expectorant which decreases the stickiness of mucus (phlegm) and helps in its removal from the airways Terbutaline is a bronchodilator. It works by relaxing the muscles in the airways and widens the airways. Together, they make breathing easier.",
    price: "",
  },
  {
    id: 2,
    images: "./images/alobest.png",
    desc: "Alobest",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 3,
    images: "./images/ambrocline-dx.png",
    desc: "Ambrocline-dx",
    price: "",
    descs: "",
  },
  {
    id: 4,
    images: "./images/freshmorn.png",
    desc: "Freshmorn",
    price: "",
    descs: "",
  },
  {
    id: 5,
    images: "./images/GlyAll.png",
    desc: "GlyAll",
    price: "",
    descs: "",
  },
  {
    id: 6,
    images: "./images/grod3.png",
    desc: "Grod3",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 7,
    images: "./images/kaaf-all.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 8,
    images: "./images/momspro.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 9,
    images: "./images/panox-40.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 10,
    images: "./images/panox-dsr.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 11,
    images: "./images/rabipass-20.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 12,
    images: "./images/rabipass-dsr.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 13,
    images: "./images/rokcool.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 14,
    images: "./images/s-9.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 15,
    images: "./images/s-oro-xt-tab.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 16,
    images: "./images/s-oro-xt.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 17,
    images: "./images/s-pregagro.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 18,
    images: "./images/S9-D.PNG",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 19,
    images: "./images/s9.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 20,
    images: "./images/s9.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 21,
    images: "./images/s9c.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 22,
    images: "./images/s9dical.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
  {
    id: 23,
    images: "./images/s9reacharge.png",
    desc: "Kaaf-All",
    price: "",
    descs: "",
    mostsell: true,
  },
  {
    id: 24,
    images: "./images/stretchfree.PNG",
    desc: "Kaaf-All",
    price: "",
    descs: "",
  },
];

export default data;
